# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: Default

variables:
  imageName: employee-login-app
  dockerUser: vishnu4447

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install -r requirements.txt
  displayName: Install Dependencies

- script: |
    docker build -t $(dockerUser)/$(imageName):$(Build.BuildId) .
  displayName: Build Docker Image

- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(dockerUser) --password-stdin
    docker push $(dockerUser)/$(imageName):$(Build.BuildId)
  displayName: Push Docker Image
